<?php

use Illuminate\Support\Facades\Schema;

/**
 * The declared index shapes on `notifications`, `comments` and `pets`.
 *
 * This is the layer that always runs. It asserts the *shape* of what the
 * migrations declare — the ordered column list of each index — because that is
 * the part of an index decision that is driver-agnostic and that genuinely
 * fails before the migration lands and passes after it.
 *
 * Two tempting alternatives are deliberately not written here:
 *
 * - A query-count assertion is structurally blind to an index. Adding one does
 *   not change how many queries a page issues, it changes what each costs, so
 *   such a test passes identically before and after and can never be shown
 *   failing first.
 * - An `EXPLAIN QUERY PLAN` assertion proves nothing about production. The
 *   suite runs SQLite in memory while dev and prod are MySQL 8, and the two
 *   optimisers differ precisely where index work lives — SQLite will happily
 *   `USE TEMP B-TREE FOR ORDER BY` where InnoDB reaches for a second index and
 *   a backward scan (.ai/rules/migrations.md). The InnoDB half of this pin
 *   lives in tests/Feature/MysqlIndexPlanTest.php, which skips off MySQL.
 *
 * Every assertion below is on the ordered column list, never on the index name:
 * names are auto-generated by the framework unless one is passed, so a rename
 * is not a regression while a reordered or missing column always is.
 */

/**
 * The ordered column list of every index declared on a table, index names
 * discarded.
 *
 * @return list<list<string>>
 */
function indexColumnLists(string $table): array
{
    return array_values(array_map(
        fn (array $index): array => array_values($index['columns']),
        Schema::getIndexes($table),
    ));
}

/**
 * The first column of every index declared on a table, deduplicated.
 *
 * The InnoDB invariant is "at least one index leads with this column", not
 * "every index mentioning this column leads with it" — the latter would reject
 * correctly designed composites, `comments_commentable_parent_created_at_index`
 * carrying `parent_id` in third position on purpose, and a future
 * `(status, user_id, ...)` on `pets` for no reason at all.
 *
 * @return list<string>
 */
function leadingIndexColumns(string $table): array
{
    return array_values(array_unique(array_map(
        fn (array $columns): string => $columns[0],
        indexColumnLists($table),
    )));
}

test('notifications indexes both bell queries on the morph pair and drops the bare morph prefix', function () {
    $indexes = indexColumnLists('notifications');

    expect($indexes)
        ->toContain(['notifiable_type', 'notifiable_id', 'created_at'])
        ->toContain(['notifiable_type', 'notifiable_id', 'read_at'])
        ->not->toContain(['notifiable_type', 'notifiable_id']);
});

test('comments indexes the reply listing and the root thread listing and drops the bare morph prefix', function () {
    $indexes = indexColumnLists('comments');

    /**
     * The morph pair is hand-written as two plain columns rather than
     * `$table->morphs('commentable')` precisely so the redundant
     * `(commentable_type, commentable_id)` index is never declared — it is a
     * strict prefix of the four-column composite below, so it narrows nothing
     * and costs a write per insert (.ai/rules/migrations.md). A "tidy" back to
     * `morphs()` reinstates it while every other assertion here stays green,
     * which is what the absence assertion is for.
     */
    expect($indexes)
        ->toContain(['parent_id', 'created_at'])
        ->toContain(['commentable_type', 'commentable_id', 'parent_id', 'created_at'])
        ->not->toContain(['commentable_type', 'commentable_id']);
});

test('pets indexes the profile listings query and carries neither superseded single-column index', function () {
    /**
     * The bare `user_id` and `status` indexes were both removed when the
     * composites that supersede them landed: each is a strict prefix of one, so
     * it narrows nothing a query can use and only costs a write. Without these
     * absence assertions a re-added single-column index passes silently —
     * `toContain` on the composite is satisfied either way.
     */
    expect(indexColumnLists('pets'))
        ->toContain(['user_id', 'deleted_at', 'created_at'])
        ->not->toContain(['user_id'])
        ->not->toContain(['status']);
});

test('every filtered foreign key and morph column leads an index of its own', function () {
    /**
     * InnoDB creates its own foreign key index only when no suitable one
     * exists, and it is the *leading* column that makes an index suitable. Bury
     * a foreign key behind another column in every index that mentions it and
     * InnoDB silently generates a second index under a name nobody chose.
     *
     * The invariant is per column, not per index: `parent_id` sits third in
     * `comments_commentable_parent_created_at_index` deliberately, and that is
     * fine because `comments_parent_id_created_at_index` leads with it.
     */
    expect(leadingIndexColumns('pets'))->toContain('user_id');

    expect(leadingIndexColumns('comments'))
        ->toContain('user_id')
        ->toContain('parent_id')
        ->toContain('commentable_type');
});

test('pets no longer carries the city and state index no query could read', function () {
    /**
     * The only location lookup in the application is Nova's `$search`, which
     * compiles to `like '%term%'`. A leading wildcard can never use a B-tree,
     * so the index was written on every insert and read by nothing.
     *
     * The positive assertion is paired with it on purpose: a negative-only test
     * passes just as happily over an empty haystack, so a typo'd table name or
     * a `getIndexes()` that returned nothing would look like success.
     */
    expect(indexColumnLists('pets'))
        ->toContain(['latitude', 'longitude'])
        ->not->toContain(['city', 'state']);
});

test('pets keeps the standalone created_at index', function () {
    /**
     * Reviewed alongside the composites and deliberately retained. Asserted so
     * a later cleanup cannot remove it silently on the assumption that
     * `pets_status_deleted_at_created_at_index` covers it — it does not, that
     * composite only serves a query that also pins `status`.
     */
    expect(indexColumnLists('pets'))->toContain(['created_at']);
});
